using System.Linq.Expressions;
using System.Reflection;

namespace TGHarker.Orleans.Search.Abstractions.Abstractions;

/// <summary>
/// Defines the contract for search providers that enable querying grains by their state.
/// Implementations are generated by the source generator for each queryable grain type.
/// </summary>
/// <typeparam name="TGrain">The grain interface type (e.g., IUserGrain)</typeparam>
/// <typeparam name="TState">The grain state type (e.g., UserState)</typeparam>
public interface ISearchProvider<TGrain, TState>
{
    /// <summary>
    /// Gets the queryable database set for the entity.
    /// </summary>
    /// <returns>An IQueryable that can be used to build database queries.</returns>
    IQueryable<object> GetDbSet();

    /// <summary>
    /// Gets the entity type used for database queries.
    /// </summary>
    Type EntityType { get; }

    /// <summary>
    /// Gets the grain ID property name on the entity.
    /// </summary>
    string GrainIdPropertyName => "GrainId";

    /// <summary>
    /// Maps a grain interface method call to the corresponding entity property expression.
    /// Used during LINQ expression translation.
    /// </summary>
    /// <param name="method">The grain interface method (e.g., GetEmailAsync)</param>
    /// <param name="entityParameter">The entity parameter expression</param>
    /// <returns>An expression that accesses the entity property</returns>
    Expression MapGrainMethodToEntityProperty(MethodInfo method, ParameterExpression entityParameter);

    /// <summary>
    /// Maps a grain property member to the corresponding entity property expression.
    /// Used during LINQ expression translation.
    /// </summary>
    /// <param name="member">The grain property member</param>
    /// <param name="entityParameter">The entity parameter expression</param>
    /// <returns>An expression that accesses the entity property</returns>
    Expression MapGrainPropertyToEntity(MemberInfo member, ParameterExpression entityParameter);

    /// <summary>
    /// Applies a filter to the entity query and returns matching grain IDs.
    /// </summary>
    /// <param name="predicate">A predicate expression to filter entities. The parameter is the entity type.</param>
    /// <returns>Collection of grain IDs matching the filter</returns>
    Task<List<string>> QueryWithFilterAsync(LambdaExpression predicate);

    /// <summary>
    /// Gets all grain IDs (no filter).
    /// </summary>
    Task<List<string>> GetAllGrainIdsAsync();

    /// <summary>
    /// Updates or inserts grain state into the search index.
    /// </summary>
    /// <param name="grainId">The grain identifier</param>
    /// <param name="state">The grain state to index</param>
    /// <param name="version">Version number for optimistic concurrency</param>
    /// <param name="timestamp">When this update occurred</param>
    Task UpsertAsync(string grainId, TState state, long version, DateTime timestamp);

    /// <summary>
    /// Removes a grain from the search index.
    /// </summary>
    /// <param name="grainId">The grain identifier to remove</param>
    Task DeleteAsync(string grainId);

    /// <summary>
    /// Performs full-text search across indexed text fields.
    /// </summary>
    /// <param name="query">The search query text</param>
    /// <param name="maxResults">Maximum number of results to return</param>
    /// <param name="minScore">Minimum relevance score (0.0 to 1.0)</param>
    /// <returns>Collection of grain IDs matching the search query</returns>
    Task<IEnumerable<string>> FullTextSearchAsync(string query, int maxResults, double minScore = 0.0);
}
