using Orleans;

namespace TGHarker.Orleans.Search.Abstractions.Abstractions;

/// <summary>
/// Marker interface that links a search model to its grain type.
/// Source generators create implementations of this interface for each queryable grain.
/// </summary>
/// <typeparam name="TGrain">The grain interface type this search model represents</typeparam>
/// <example>
/// // Generated by source generator:
/// public class UserSearch : ISearchModel&lt;IUserGrain&gt;
/// {
///     public string Email { get; set; }
///     public bool IsInitialized { get; set; }
/// }
/// </example>
public interface ISearchModel<TGrain> where TGrain : IGrain
{
}
